"Filed out from Dolphin Smalltalk"!

RenderCommand subclass: #DrawSurface
	instanceVariableNames: 'surface rectangle stretch'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
DrawSurface guid: (GUID fromString: '{e942f8ed-a8ee-4fa3-adba-5c858e2494f7}')!
DrawSurface comment: ''!
!DrawSurface categoriesForClass!Kernel-Objects! !
!DrawSurface methodsFor!

rectangle
	^rectangle!

rectangle: anObject
	rectangle := anObject!

stretch
	^stretch!

stretch: anObject
	stretch := anObject!

surface
	^surface!

surface: anObject
	surface := anObject! !
!DrawSurface categoriesForMethods!
rectangle!accessing!public! !
rectangle:!accessing!public! !
stretch!accessing!public! !
stretch:!accessing!public! !
surface!accessing!public! !
surface:!accessing!public! !
!

