"Filed out from Dolphin Smalltalk"!

RenderCommand subclass: #DrawRectangle
	instanceVariableNames: 'rectangle color width'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
DrawRectangle guid: (GUID fromString: '{e4359af8-1f8b-4c2f-b2b4-7d05a06a4b6a}')!
DrawRectangle comment: ''!
!DrawRectangle categoriesForClass!Kernel-Objects! !
!DrawRectangle methodsFor!

color
	^color!

color: anObject
	color := anObject!

rectangle
	^rectangle!

rectangle: anObject
	rectangle := anObject!

width
	^width!

width: anObject
	width := anObject! !
!DrawRectangle categoriesForMethods!
color!accessing!public! !
color:!accessing!public! !
rectangle!accessing!public! !
rectangle:!accessing!public! !
width!accessing!public! !
width:!accessing!public! !
!

