"Filed out from Dolphin Smalltalk"!

DrawImage subclass: #DrawJPEG
	instanceVariableNames: 'data'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
DrawJPEG guid: (GUID fromString: '{e92fb6ff-35d7-42b2-a893-49f6ada5f647}')!
DrawJPEG comment: ''!
!DrawJPEG categoriesForClass!Kernel-Objects! !
!DrawJPEG methodsFor!

data
	^data!

data: anObject
	data := anObject! !
!DrawJPEG categoriesForMethods!
data!accessing!public! !
data:!accessing!public! !
!

