"Filed out from Dolphin Smalltalk"!

Smalltalk at: #TTFConstants put: (PoolConstantsDictionary named: #TTFConstants)!
TTFConstants at: 'TTF_HINTING_LIGHT' put: 16r1!
TTFConstants at: 'TTF_HINTING_MONO' put: 16r2!
TTFConstants at: 'TTF_HINTING_NONE' put: 16r3!
TTFConstants at: 'TTF_HINTING_NORMAL' put: 16r0!
TTFConstants at: 'TTF_STYLE_BOLD' put: 16r1!
TTFConstants at: 'TTF_STYLE_ITALIC' put: 16r2!
TTFConstants at: 'TTF_STYLE_NORMAL' put: 16r0!
TTFConstants at: 'TTF_STYLE_STRIKETHROUGH' put: 16r8!
TTFConstants at: 'TTF_STYLE_UNDERLINE' put: 16r4!
TTFConstants at: 'TTF_WRAPPED_ALIGN_CENTER' put: 16r1!
TTFConstants at: 'TTF_WRAPPED_ALIGN_LEFT' put: 16r0!
TTFConstants at: 'TTF_WRAPPED_ALIGN_RIGHT' put: 16r2!
TTFConstants shrink!
