"Filed out from Dolphin Smalltalk"!

Object subclass: #Camera
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

Camera guid: (GUID fromString: '{4ee168d3-0665-45d4-bf8e-d58827d52ce8}')!

Camera comment: ''!

!Camera categoriesForClass!Kernel-Objects! !

!Camera class methodsFor!

new
	^super new initialize! !

!Camera class categoriesForMethods!
new!public! !
!

