"Filed out from Dolphin Smalltalk"!

MatrixError subclass: #NonSquareMatrixError
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

NonSquareMatrixError guid: (GUID fromString: '{ac2c4181-916d-4b0c-aab2-82978cb02700}')!

NonSquareMatrixError comment: 'An error of this class is signalled when a square matrix is required for an operation but a non-square matrix is found.'!

!NonSquareMatrixError categoriesForClass!Unclassified! !

