"Filed out from Dolphin Smalltalk"!

DrawText subclass: #DrawString
	instanceVariableNames: 'string format'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

DrawString guid: (GUID fromString: '{273828c6-dafe-4135-b556-04cda45a2564}')!

DrawString comment: ''!

!DrawString categoriesForClass!Kernel-Objects! !

!DrawString methodsFor!

format
	^format!

format: anObject
	format := anObject!

string
	^string!

string: anObject
	string := anObject! !

!DrawString categoriesForMethods!
format!accessing!public! !
format:!accessing!public! !
string!accessing!public! !
string:!accessing!public! !
!

