"Filed out from Dolphin Smalltalk"!

DrawImage subclass: #DrawSurface
	instanceVariableNames: 'surface'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

DrawSurface guid: (GUID fromString: '{e942f8ed-a8ee-4fa3-adba-5c858e2494f7}')!

DrawSurface comment: ''!

!DrawSurface categoriesForClass!Kernel-Objects! !

!DrawSurface methodsFor!

surface
	^surface!

surface: anObject
	surface := anObject! !

!DrawSurface categoriesForMethods!
surface!accessing!public! !
surface:!accessing!public! !
!

