"Filed out from Dolphin Smalltalk"!

RenderCommand subclass: #DrawString
	instanceVariableNames: 'color font rectangle fontSize fontStyle format string'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

DrawString guid: (GUID fromString: '{3bd8bdbd-fd9a-400b-b677-a972c22853c6}')!

DrawString comment: ''!

!DrawString categoriesForClass!Kernel-Objects! !

!DrawString methodsFor!

color
	^color!

color: anObject
	color := anObject!

font
	^font!

font: anObject
	font := anObject!

fontName
	^nil!

fontSize
	^fontSize!

fontSize: anInteger
	fontSize := anInteger!

fontStyle
	^fontStyle!

fontStyle: anObject
	fontStyle := anObject!

format
	^format!

format: anObject
	format := anObject!

rectangle
	^rectangle!

rectangle: anObject
	rectangle := anObject!

string
	^string!

string: anObject
	string := anObject! !

!DrawString categoriesForMethods!
color!accessing!public! !
color:!accessing!public! !
font!accessing!public! !
font:!accessing!public! !
fontName!public! !
fontSize!accessing!public! !
fontSize:!public! !
fontStyle!accessing!public! !
fontStyle:!accessing!public! !
format!accessing!public! !
format:!accessing!public! !
rectangle!accessing!public! !
rectangle:!accessing!public! !
string!accessing!public! !
string:!accessing!public! !
!

