"Filed out from Dolphin Smalltalk"!

DrawImage subclass: #DrawTexture
	instanceVariableNames: 'texture'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

DrawTexture guid: (GUID fromString: '{9c54abcc-ece9-4793-a9b1-77a901533e9b}')!

DrawTexture comment: ''!

!DrawTexture categoriesForClass!Kernel-Objects! !

!DrawTexture methodsFor!

texture
	^texture!

texture: anObject
	texture := anObject! !

!DrawTexture categoriesForMethods!
texture!accessing!public! !
texture:!accessing!public! !
!

