"Filed out from Dolphin Smalltalk"!

RenderCommand subclass: #DrawText
	instanceVariableNames: 'text rectangle color'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

DrawText guid: (GUID fromString: '{3752de07-922d-4285-a83c-1b728fed4a50}')!

DrawText comment: ''!

!DrawText categoriesForClass!Kernel-Objects! !

!DrawText methodsFor!

color
	^color!

color: anObject
	color := anObject!

rectangle
	^rectangle!

rectangle: anObject
	rectangle := anObject!

text
	^text!

text: anObject
	text := anObject! !

!DrawText categoriesForMethods!
color!accessing!public! !
color:!accessing!public! !
rectangle!accessing!public! !
rectangle:!accessing!public! !
text!accessing!public! !
text:!accessing!public! !
!

