"Filed out from Dolphin Smalltalk"!

RenderCommand subclass: #DrawBezierCurve
	instanceVariableNames: 'points color curve width'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
DrawBezierCurve guid: (GUID fromString: '{6c1c924f-fec0-4f22-ac25-1d4ab5da81bf}')!
DrawBezierCurve comment: ''!
!DrawBezierCurve categoriesForClass!Unclassified! !
!DrawBezierCurve methodsFor!

color
	^color!

color: anObject
	color := anObject!

points
	^points!

points: anObject
	points := anObject!

width
	^width!

width: anObject
	width := anObject! !
!DrawBezierCurve categoriesForMethods!
color!public! !
color:!public! !
points!public! !
points:!public! !
width!public! !
width:!public! !
!

