"Filed out from Dolphin Smalltalk"!

RenderCommand subclass: #DrawText
	instanceVariableNames: 'color font rectangle fontSize fontStyle'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

DrawText guid: (GUID fromString: '{3bd8bdbd-fd9a-400b-b677-a972c22853c6}')!

DrawText comment: ''!

!DrawText categoriesForClass!Kernel-Objects! !

!DrawText methodsFor!

color
	^color!

color: anObject
	color := anObject!

font
	^font!

font: anObject
	font := anObject!

fontName
	^nil!

fontSize
	^fontSize!

fontSize: anInteger
	fontSize := anInteger!

fontStyle
	^fontStyle!

fontStyle: anObject
	fontStyle := anObject!

rectangle
	^rectangle!

rectangle: anObject
	rectangle := anObject! !

!DrawText categoriesForMethods!
color!accessing!public! !
color:!accessing!public! !
font!accessing!public! !
font:!accessing!public! !
fontName!public! !
fontSize!accessing!public! !
fontSize:!public! !
fontStyle!accessing!public! !
fontStyle:!accessing!public! !
rectangle!accessing!public! !
rectangle:!accessing!public! !
!

