"Filed out from Dolphin Smalltalk"!

DrawText subclass: #DrawCharacter
	instanceVariableNames: 'character'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
DrawCharacter guid: (GUID fromString: '{2c835f33-acba-4114-9e01-679cd3df4f18}')!
DrawCharacter comment: ''!
!DrawCharacter categoriesForClass!Kernel-Objects! !
!DrawCharacter methodsFor!

character
	^character!

character: anObject
	character := anObject! !
!DrawCharacter categoriesForMethods!
character!accessing!public! !
character:!accessing!public! !
!

