"Filed out from Dolphin Smalltalk"!

RenderCommand subclass: #DrawBitmap
	instanceVariableNames: 'bitmap rectangle'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
DrawBitmap guid: (GUID fromString: '{64c6d78f-53ac-43e4-84fe-88f503bc8aeb}')!
DrawBitmap comment: ''!
!DrawBitmap categoriesForClass!Kernel-Objects! !
!DrawBitmap methodsFor!

bitmap
	^bitmap!

bitmap: anObject
	bitmap := anObject!

rectangle
	^rectangle!

rectangle: anObject
	rectangle := anObject! !
!DrawBitmap categoriesForMethods!
bitmap!accessing!public! !
bitmap:!accessing!public! !
rectangle!accessing!public! !
rectangle:!accessing!public! !
!

