"Filed out from Dolphin Smalltalk"!

FillCommand subclass: #FillPolygon
	instanceVariableNames: 'points'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
FillPolygon guid: (GUID fromString: '{de6ab2ee-3965-49a1-90e3-23bffc918c91}')!
FillPolygon comment: ''!
!FillPolygon categoriesForClass!Kernel-Objects! !
!FillPolygon methodsFor!

points
	^points!

points: anObject
	points := anObject! !
!FillPolygon categoriesForMethods!
points!accessing!public! !
points:!accessing!public! !
!

