"Filed out from Dolphin Smalltalk"!

FillCommand subclass: #FillGeometry
	instanceVariableNames: 'vertices'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

FillGeometry guid: (GUID fromString: '{c0e7715d-668a-4253-a0aa-c1448f0af2eb}')!

FillGeometry comment: ''!

!FillGeometry categoriesForClass!Kernel-Objects! !

!FillGeometry methodsFor!

vertices
	^vertices!

vertices: anArrayOfVertices
	vertices := anArrayOfVertices! !

!FillGeometry categoriesForMethods!
vertices!public! !
vertices:!public! !
!

