"Filed out from Dolphin Smalltalk"!

FillGeometry subclass: #FillTriangle
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

FillTriangle guid: (GUID fromString: '{56c6ac68-c0a2-4b7e-a2f9-bb20b048164c}')!

FillTriangle comment: ''!

!FillTriangle categoriesForClass!Kernel-Objects! !

!FillTriangle methodsFor!

vertices
	^vertices!

vertices: anArrayOfVertices
	vertices := anArrayOfVertices! !

!FillTriangle categoriesForMethods!
vertices!public! !
vertices:!public! !
!

