"Filed out from Dolphin Smalltalk"!

FillGeometry subclass: #FillQuadrilateral
	instanceVariableNames: 'vertexOne vertexTwo vertexThree vertexFour'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

FillQuadrilateral guid: (GUID fromString: '{87549300-4a7b-4af5-b39e-83a1a8d4397a}')!

FillQuadrilateral comment: ''!

!FillQuadrilateral categoriesForClass!Kernel-Objects! !

