"Filed out from Dolphin Smalltalk"!

RenderCommand subclass: #FillCommand
	instanceVariableNames: 'color'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
FillCommand guid: (GUID fromString: '{9345b0a7-07e4-47aa-b397-b75143ed37c5}')!
FillCommand comment: ''!
!FillCommand categoriesForClass!Kernel-Objects! !
!FillCommand methodsFor!

color
	^color!

color: anObject
	color := anObject! !
!FillCommand categoriesForMethods!
color!accessing!public! !
color:!accessing!public! !
!

