"Filed out from Dolphin Smalltalk"!

SDL_Event subclass: #SDL_SysWMEvent
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SDL_SysWMEvent guid: (GUID fromString: '{ea8fb59c-d99c-4258-afe7-73d2d2384e77}')!

SDL_SysWMEvent comment: ''!

!SDL_SysWMEvent categoriesForClass!External-Data-Structured! !

!SDL_SysWMEvent class methodsFor!

defineFields
	self byteSize: 128! !

!SDL_SysWMEvent class categoriesForMethods!
defineFields!public! !
!

