"Filed out from Dolphin Smalltalk"!

SDL_Object subclass: #SDL_GPUBuffer
	instanceVariableNames: 'size'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SDL_GPUBuffer guid: (GUID fromString: '{d02bbb59-84e7-47e1-a8a7-367bf859f26c}')!

SDL_GPUBuffer comment: ''!

!SDL_GPUBuffer categoriesForClass!External-Data-Structured! !

!SDL_GPUBuffer methodsFor!

size
	^size!

size: anObject
	size := anObject! !

!SDL_GPUBuffer categoriesForMethods!
size!accessing!public! !
size:!accessing!public! !
!

