"Filed out from Dolphin Smalltalk"!

SDL_Event subclass: #SDL_AudioDeviceEvent
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SDL_AudioDeviceEvent guid: (GUID fromString: '{8d2fc7ba-75da-40da-a4dc-d164fa29f833}')!

SDL_AudioDeviceEvent comment: ''!

!SDL_AudioDeviceEvent categoriesForClass!External-Data-Structured! !

!SDL_AudioDeviceEvent class methodsFor!

defineFields
	self byteSize: 128! !

!SDL_AudioDeviceEvent class categoriesForMethods!
defineFields!public! !
!

