"Filed out from Dolphin Smalltalk"!

SDL_Event subclass: #SDL_DisplayEvent
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SDL_DisplayEvent guid: (GUID fromString: '{e2d7d1d6-cc38-49e1-908c-3bee210fa08c}')!

SDL_DisplayEvent comment: ''!

!SDL_DisplayEvent categoriesForClass!External-Data-Structured! !

!SDL_DisplayEvent class methodsFor!

defineFields
	self byteSize: 128! !

!SDL_DisplayEvent class categoriesForMethods!
defineFields!public! !
!

