"Filed out from Dolphin Smalltalk"!

SDL_Event subclass: #SDL_PaintEvent
	instanceVariableNames: 'canvas'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SDL_PaintEvent guid: (GUID fromString: '{6a9cfd06-12f3-4b41-8b6a-c565f96d220e}')!

SDL_PaintEvent comment: ''!

!SDL_PaintEvent categoriesForClass!External-Data-Structured! !

!SDL_PaintEvent methodsFor!

canvas
	^canvas!

canvas: anObject
	canvas := anObject! !

!SDL_PaintEvent categoriesForMethods!
canvas!accessing!public! !
canvas:!accessing!public! !
!

