"Filed out from Dolphin Smalltalk"!

SDL_Object subclass: #SDL_GPUTransferBuffer
	instanceVariableNames: 'size'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SDL_GPUTransferBuffer guid: (GUID fromString: '{27e6b821-657c-45c8-b0ce-6de46871dca7}')!

SDL_GPUTransferBuffer comment: ''!

!SDL_GPUTransferBuffer categoriesForClass!External-Data-Structured! !

!SDL_GPUTransferBuffer methodsFor!

size
	^size!

size: anInteger
	size := anInteger! !

!SDL_GPUTransferBuffer categoriesForMethods!
size!public! !
size:!public! !
!

